// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-MBswBEd9_C-T354RK0vwQ-BZfV2fkaU',
    appId: '1:379971228254:web:219a6c289d3b0dd100dacf',
    messagingSenderId: '379971228254',
    projectId: 'fatkulumarproject-firebase',
    authDomain: 'fatkulumarproject-firebase.firebaseapp.com',
    databaseURL: 'https://fatkulumarproject-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fatkulumarproject-firebase.firebasestorage.app',
    measurementId: 'G-0F12V48YWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkX_1eFQyjT1vQhafzuyotKxYHsgJV2N8',
    appId: '1:379971228254:android:e6f3eef67f60ab2d00dacf',
    messagingSenderId: '379971228254',
    projectId: 'fatkulumarproject-firebase',
    databaseURL: 'https://fatkulumarproject-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fatkulumarproject-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPqwN2sPIx2BDxsQEg14ELOH3AMAYwYrk',
    appId: '1:379971228254:ios:151673b9186be1b600dacf',
    messagingSenderId: '379971228254',
    projectId: 'fatkulumarproject-firebase',
    databaseURL: 'https://fatkulumarproject-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fatkulumarproject-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPqwN2sPIx2BDxsQEg14ELOH3AMAYwYrk',
    appId: '1:379971228254:ios:151673b9186be1b600dacf',
    messagingSenderId: '379971228254',
    projectId: 'fatkulumarproject-firebase',
    databaseURL: 'https://fatkulumarproject-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fatkulumarproject-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-MBswBEd9_C-T354RK0vwQ-BZfV2fkaU',
    appId: '1:379971228254:web:e7a101c74243b2b600dacf',
    messagingSenderId: '379971228254',
    projectId: 'fatkulumarproject-firebase',
    authDomain: 'fatkulumarproject-firebase.firebaseapp.com',
    databaseURL: 'https://fatkulumarproject-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fatkulumarproject-firebase.firebasestorage.app',
    measurementId: 'G-KW8F3GL6T8',
  );
}
